---
title: "Soil Collection Map"
author: "Sam Muir"
date: "2022-09-22"
output: html_document
---
```{r}
library(usmap)
library(tidyverse)
library(ggplot2)
library(maptools)
library(ggrepel)
library(viridis)
```


```{r}
soil <- read_csv("soil_collection.csv") %>%
  rename(lon = long) 
  

soil_trans <- usmap_transform(soil) %>%
  mutate(site = case_when(site == "chapman" ~ "Chapman State Park",
                   site == "point_lookout" ~ "Point Lookout State Park",
                   site == "chapel" ~ "Chapel Point State Park",
                   site == "newtowne" ~ "Newtowne Neck State Park"))
```

```{r}
plot_usmap("counties", fill = "lightgreen", alpha = 0.25,
           include = c("24037", "24009", "24017", "24033"),
           labels = T) +
  geom_point(data = soil_trans, aes(x = x, y = y, color = salinity_ppt),
             size = 4) +
  theme(legend.position = "right", text = element_text(size = 12)) +
  labs(color = "Salinity (ppt)") +
   ggrepel::geom_label_repel(data = soil_trans,
             aes(x = x, y = y, label = site),
             size = 3, alpha = 1,
             box.padding = 0.5,
             label.r = unit(0.15, "lines"), label.size = 0.5,
             seed = 1002) +
  scale_color_viridis(end = 0.8)
```

